const ActionTypes = {
  SET_CURRENT_USER: '@auth/SET_CURRENT_USER',
  GOOGLE_SIGN_IN_REQUEST: '@auth/GOOGLE_SIGN_IN_REQUEST',
  EMAIL_SIGN_IN_REQUEST: '@auth/EMAIL_SIGN_IN_REQUEST',
  SIGN_SUCCESS: '@auth/SIGN_SUCCESS',
  SIGN_FAILURE: '@auth/SIGN_FAILURE',
  SIGN_UP_REQUEST: '@auth/SIGN_UP_REQUEST',
  CREATE_USER: '@auth/CREATE_USER',
  SIGN_OUT_REQUEST: '@auth/SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: '@auth/SIGN_OUT_SUCCESS',
};

export default ActionTypes;
