export enum ActionTypes {
  SET_CURRENT_USER = '@auth/SET_CURRENT_USER',
  GOOGLE_SIGN_IN_START = '@auth/GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START = '@auth/EMAIL_SIGN_IN_START',
  GOOOGLE_SIGNIN_SUCCESS = '@auth/GOOOGLE_SIGNIN_SUCCESS',
  CREATE_USER = '@auth/CREATE_USER',
  EMAIL_SIGN_IN_SUCCESS = '@auth/SIGN_IN_SUCCESS',
  SIGN_FAILURE = '@auth/SIGN_FAILURE',
  SIGN_OUT = '@auth/SIGN_OUT',
}
