export enum ActionTypes {
  SET_CURRENT_USER = '@auth/SET_CURRENT_USER',
  GOOGLE_SIGN_IN_START = '@auth/GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START = '@auth/EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS = '@auth/SIGN_IN_SUCCESS',
  SIGN_UP_START = '@auth/SIGN_UP_START',
  SIGN_UP_SUCCESS = '@auth/SIGN_UP_SUCCESS',
  SIGN_FAILURE = '@auth/SIGN_FAILURE',
  CREATE_USER = '@auth/CREATE_USER',
  SIGN_OUT_START = '@auth/SIGN_OUT_START',
  SIGN_OUT_SUCCESS = '@auth/SIGN_OUT_SUCCESS',
}
