const ActionTypes = {
  CREATE_TRUCK_PROFILE_SUCCESS: '@truckProfile/CREATE_TRUCK_PROFILE_SUCCESS',
  CREATE_TRUCK_PROFILE_REQUEST: '@truckProfile/CREATE_TRUCK_PROFILE_REQUEST',
  TRUCK_PROFILE_FAILTURE: '@truckProfile/TRUCK_PROFILE_FAILTURE',
  UPDATE_TRUCK_PROFILE: '@truckProfile/UPDATE_TRUCK_PROFILE',
  DELETE_TRUCK_PROFILE: '@truckProfile/DELETE_TRUCK_PROFILE',
  LOAD_TRUCK_PROFILE_SUCCESS: '@truckProfile/LOAD_TRUCK_PROFILE_SUCCESS',
  LOAD_TRUCK_PROFILE_REQUEST: '@truckProfile/LOAD_TRUCK_PROFILE_REQUEST',
};

export default ActionTypes;
