const ActionTypes = {
  CREATE_TRUCK_PROFILE_SUCCESS: '@truckProfile/CREATE_TRUCK_PROFILE_SUCCESS',
  CREATE_TRUCK_PROFILE_REQUEST: '@truckProfile/CREATE_TRUCK_PROFILE_REQUEST',
  CREATE_TRUCK_PROFILE_FAILURE: '@truckProfile/CREATE_TRUCK_PROFILE_FAILURE',
  UPDATE_TRUCK_PROFILE_REQUEST: '@truckProfile/UPDATE_TRUCK_PROFILE_REQUEST',
  UPDATE_TRUCK_PROFILE_SUCCESS: '@truckProfile/UPDATE_TRUCK_PROFILE_SUCCESS',
  UPDATE_TRUCK_PROFILE_FAILTURE: '@truckProfile/UPDATE_TRUCK_PROFILE_FAILTURE',
  DELETE_TRUCK_PROFILE_REQUEST: '@truckProfile/DELETE_TRUCK_PROFILE_REQUEST',
  DELETE_TRUCK_PROFILE_SUCCESS: '@truckProfile/DELETE_TRUCK_PROFILE_SUCCESS',
  DELETE_TRUCK_PROFILE_FAILURE: '@truckProfile/DELETE_TRUCK_PROFILE_FAILURE',
  LOAD_TRUCK_PROFILE_REQUEST: '@truckProfile/LOAD_TRUCK_PROFILE_REQUEST',
  LOAD_TRUCK_PROFILE_SUCCESS: '@truckProfile/LOAD_TRUCK_PROFILE_SUCCESS',
  LOAD_TRUCK_PROFILE_FAILURE: '@truckProfile/LOAD_TRUCK_PROFILE_FAILURE',
};

export default ActionTypes;
