const ActionTypes = {
  LOAD_MENUS_REQUEST: '@menus/LOAD_MENUS_REQUEST',
  LOAD_MENUS_SUCCESS: '@menus/LOAD_MENUS_SUCCESS',
  LOAD_MENUS_FAILURE: '@menus/LOAD_MENUS_FAILURE',
  LOAD_MENUS_BY_TYPES_REQUEST: '@menus/LOAD_MENUS_BY_TYPES_REQUEST',
  LOAD_MENUS_BY_TYPES_SUCCESS: '@menus/LOAD_MENUS_BY_TYPES_SUCCESS',
  LOAD_MENUS_BY_TYPES_FAILURE: '@menus/LOAD_MENUS_BY_TYPES_FAILURE',
  CREATE_MENU_REQUEST: '@menus/CREATE_MENU_REQUEST',
  CREATE_MENU_SUCCESS: '@menus/CREATE_MENU_SUCCESS',
  CREATE_MENU_FAILTURE: '@menus/CREATE_MENU_FAILTURE',
  UPDATE_MENU_REQUEST: '@menus/UPDATE_MENU_REQUEST',
  UPDATE_MENU_SUCCESS: '@menus/UPDATE_MENU_SUCCESS',
  UPDATE_MENU_FAILURE: '@menus/UPDATE_MENU_FAILURE',
  DELETE_MENU_REQUEST: '@menus/DELETE_MENU_REQUEST',
  DELETE_MENU_SUCCESS: '@menus/DELETE_MENU_SUCCESS',
  DELETE_MENU_FAILTURE: '@menus/DELETE_MENU_FAILTURE',
};

export default ActionTypes;
