const ActionTypes = {
  LOAD_SCHEDULES_REQUEST: '@schedules/LOAD_SCHEDULES_REQUEST',
  LOAD_SCHEDULES_SUCCESS: '@schedules/LOAD_SCHEDULES_SUCCESS',
  CREATE_SCHEDULE_REQUEST: '@schedules/CREATE_SCHEDULE_REQUEST',
  CREATE_SCHEDULE_SUCCESS: '@schedules/CREATE_SCHEDULE_SUCCESS',
  SCHEDULES_FAILURE: '@schedules/SCHEDULES_FAILURE',
};

export default ActionTypes;
