const ActionTypes = {
  LOAD_SCHEDULES_REQUEST: '@schedules/LOAD_SCHEDULES_REQUEST',
  LOAD_SCHEDULES_SUCCESS: '@schedules/LOAD_SCHEDULES_SUCCESS',
  LOAD_MONTH_SCHEDULES_REQUEST: '@schedules/LOAD_MONTH_SCHEDULES_REQUEST',
  LOAD_MONTH_SCHEDULES_SUCCESS: '@schedules/LOAD_MONTH_SCHEDULES_SUCCESS',
  LOAD_MONTH_SCHEDULES_FAILURE: '@schedules/LOAD_MONTH_SCHEDULES_FAILURE',
  CREATE_SCHEDULE_REQUEST: '@schedules/CREATE_SCHEDULE_REQUEST',
  CREATE_SCHEDULE_SUCCESS: '@schedules/CREATE_SCHEDULE_SUCCESS',
  CREATE_SCHEDULE_FAILTURE: '@schedules/CREATE_SCHEDULE_FAILTURE',
  UPDATE_SCHEDULE_REQUEST: '@schedules/UPDATE_SCHEDULE_REQUEST',
  UPDATE_SCHEDULE_SUCCESS: '@schedules/UPDATE_SCHEDULE_SUCCESS',
  UPDATE_SCHEDULE_FAILURE: '@schedules/UPDATE_SCHEDULE_FAILURE',
  DELETE_SCHEDULE_REQUEST: '@schedules/DELETE_SCHEDULE_REQUEST',
  DELETE_SCHEDULE_SUCCESS: '@schedules/DELETE_SCHEDULE_SUCCESS',
  DELETE_SCHEDULE_FAILTURE: '@schedules/DELETE_SCHEDULE_FAILTURE',
};

export default ActionTypes;
